### ISSUE TITLE
`SwiftBasicFormat` isn't formatting `try?` correctly

### ISSUE THREAD

**Issue by stevapple** [swiftlang/swift-syntax#1141]
### Description

Currently `SwiftBasicFormat` will format `try?` as `try ?`, which is a false syntax rejected by the Swift compiler.

### Steps to Reproduce

```swift
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftBasicFormat

class CodeGenerationFormat: BasicFormat {
  override var indentation: TriviaPiece { .spaces(indentationLevel * 2) }
}

let sourceFile = SourceFile {
    ImportDecl("import Foundation")
    VariableDecl("let url = URL(string: \"https://www.swift.org\")")
    VariableDecl("let content = try? String(contentsOf: url)")
}

print(sourceFile.formatted(using: CodeGenerationFormat()))
```

Output:
```swift
import Foundation
let url = URL(string: "https://www.swift.org")
let content = try ? String(contentsOf: url)
// main.swift:3:18 Consecutive statements on a line must be separated by ';'
// main.swift:3:19 Expected initial value after '='
// main.swift:3:19 Expected expression
```

**Comment by stevapple** [comment]
It could also be noticed that the compiler diagnostic isn't quite helpful regarding this bug — shall we also open a bug report in `apple/swift`?

**Comment by ahoppen** [comment]
rdar://103334147

**Comment by ahoppen** [comment]
Thanks for the bug report. @kimdv is already working on a fix for it.

> It could also be noticed that the compiler diagnostic isn't quite helpful regarding this bug — shall we also open a bug report in apple/swift?

Absolutely. Since this should be a parser bug, you can actually file it as an issue against the new parser in this repository: https://github.com/apple/swift-syntax/issues/new?assignees=&labels=bug%2CSwiftParser&template=PARSER_BUG.yml

The new parser doesn’t generate errors during normal compilation yet but I’m hoping that that should change soon.
