### ISSUE TITLE
cast patternBinding.pattern to IdentifierPatternSyntax failed

### ISSUE THREAD

**Issue by seaai** [swiftlang/swift-syntax#1990]
### Issue Kind

Other

### Source Code

```
import SwiftSyntax
import SwiftSyntaxParser

class BugReproduce {
    func test() {
        let source = """
var myVariable = 42
"""
        let sourceFile = try! SyntaxParser.parse(source: source)
        TestSyntaxVisitor(viewMode: .all).walk(sourceFile)
    }
}

class TestSyntaxVisitor: SyntaxVisitor {
    override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
        for patternBinding in node.bindings {
            print("1: ", patternBinding.pattern.customMirror.subjectType) // 1:  IdentifierPatternSyntax
            print("2: ", patternBinding.pattern.kind) // 2:  identifierPattern
            print("3: ", patternBinding.pattern.is(IdentifierPatternSyntax.self)) // 3:  true
            
            let identifierPattern = patternBinding.pattern as! IdentifierPatternSyntax // failed
            print("4: ", identifierPattern.identifier.text)
        }
        return .visitChildren
    }
}

```

### Description

Hello, as the test source code, I expected the 4th print would output "myVariable", however Xcode noticed that "Cast from 'PatternSyntax' to unrelated type 'IdentifierPatternSyntax' always fails", and at runtime there was an error "Thread 1: Swift runtime failure: failed cast"

my swift-syntax version is 5.0.8, and Xcode version is 14.3.1

output in test code as follow:
1:  IdentifierPatternSyntax
2:  identifierPattern
3:  true

I was confused, was it a bug or I didn't use it in a right way? Hope to get a clue here, thanks a lot.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113309680

**Comment by allevato** [comment]
For performance reasons, SwiftSyntax nodes are value types that don't follow the same kinds of protocol or class hierarchical relationships that would allow you to use `as`-casts. Instead, they provide a similar `as()` method that lets you "cast" a node and get an instance of it that's the new type.

So instead of this,

```swift
let identifierPattern = patternBinding.pattern as! IdentifierPatternSyntax // failed
```

you need to write

```swift
let identifierPattern = patternBinding.pattern.as(IdentifierPatternSyntax.self)!
```

And of course, it's a good idea to replace the force unwrap with an optional check, because you can also have syntax like this:

```swift
let (x, y) = (foo(), bar())
```

where the pattern binding isn't an `IdentifierPattern` but instead a `TuplePattern`.
