### ISSUE TITLE
 error: failed to receive result from plugin

### ISSUE THREAD

**Issue by ssly1997** [swiftlang/swift-syntax#2029]
### Description

The latest version of Xcode 15 beta 5, build number 15A5209g, encountered errors while running previously written macros. The error message is: 'failed to receive result from plugin (from macro ‘XXX').
It was working fine in earlier versions of Xcode 15 beta.

**Comment by Matejkob** [comment]
By any chance, do you have an example of such a macro in the public domain?

**Comment by ssly1997** [comment]
> By any chance, do you have an example of such a macro in the public domain that I could take a look at?

https://github.com/ssly1997/Icarus
This is the code

**Comment by ssly1997** [comment]
> By any chance, do you have an example of such a macro in the public domain that I could take a look at?

I just tried it, and this macro works on this version of Xcode:  Version 15.0 beta 2 (15A5161b)

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113567668

**Comment by bnbarham** [comment]
This is due to a change in the compiler to instead send model conformance macros as extensions. You'll need to update your swift-syntax to the latest version, though please note that some of the changes will require updates to `Icarus` as well:
https://forums.swift.org/t/significant-changes-in-the-latest-swift-syntax-509-prerelease/66644

Specifically for your case:
  - `ConformanceMacro` is now handled by `ExtensionMacro`
  - `binding.accessor` is `binding.accessorBlock?.accessors` (which is either accessors or the getter) and thus `node.accessors` will now be `node`
  - Otherwise there's just a few renames, but those are just deprecated so shouldn't block building.
