### ISSUE TITLE
Outdated SwiftSyntaxBuilder APIs in latest releases

### ISSUE THREAD

**Issue by evnik** [swiftlang/swift-syntax#971]
### Description

I think SwiftSyntaxBuilder APIs, like expression convenience initializers, should be available in the latest releases of SwiftSyntax (e.g. `0.50700.1`), because those APIs were added before the release. However those APIs can't be resolved if `0.50700.1` is targeted. And I even don't see the `0.50700.1` tag in the repo. On browsing that tag GitHub [says](https://github.com/apple/swift-syntax/tree/0.50700.1) 
> ⚠️ This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

### Steps to Reproduce

1. Add SwiftSyntax to the `Package.swift` manifest as `.package(name: "SwiftSyntax", url: "https://github.com/apple/swift-syntax.git", .exact("0.50700.1"))`
2. Let SPM to resolve dependencies
3. Declare empty dictionary expression `let d = DictionaryExpr()`
4. Observe compilation fails with error "missing argument for parameter 'content' in call" while it should be resolved as initializer declared in the [`DictionaryExprConvenienceInitializers.swift`](https://github.com/apple/swift-syntax/blob/main/Sources/SwiftSyntaxBuilder/ConvenienceInitializers/DictionaryExprConvenienceInitializers.swift#L18)

**Comment by ahoppen** [comment]
rdar://101277693

**Comment by ahoppen** [comment]
## `0.50700.1` is not part of any branch

The `0.50700.1` release was branched off the `release/5.7` branch to declare the static parser library dependency. If you look a the parent commit of this tag, you will notice that it’s the current tip of `release/5.7`. We do it this way because the included parser library needs to exactly match the syntax tree layout that is used in SwiftSyntax and if we referenced a parser library in release/5.7, things would break if we merge a commit that modifies the syntax tree layout.

## The convenience initializer is not in the `0.50700.1` release

While this convenience initializer was merged before `0.50700.1` was released, it was only merged into `main` and not `release/5.7` and is thus not available in the release yet. This is expected. If you want to use SwiftSyntaxBuilder, I would encourage you to use `main` because it contains quite a few more changes that make the API easier to use, most notably the changes that allowed https://github.com/apple/swift-syntax/pull/856. Be aware though that SwiftSyntaxBuilder is still in-development and the API will probably continue to evolve.

**Comment by evnik** [comment]
@ahoppen While exact version of the parser library is definitely important for SwiftSyntax release, I don't understand why can't compatible convenience initializers be backported to the release branch?
You can't really ask third party projects to refer the `main` branch because it isn't stable. And pining to a commit identifier also isn't a good way because it doesn't give any clue on why the one commit is replaced with another.
I see there are `swift-DEVELOPMENT-SNAPSHOT-yyyy-MM-dd-a` tags, but it isn't clear if I can use them to pin to a specific version of the `main` branch. Could you please confirm that?

**Comment by ahoppen** [comment]
This is fundamental to our release process. Basically, the 5.7 release is done and we are only providing critical bug fixes for it. If we pulled every change from main to release/5.7, there would be very benefit of having releases at all. `0.50700.1` happens to contain whatever it contains and if you want a more recent version, you need to use releases from `main`. Using a swift development snapshot tag should totally work. If you are seeing any issues with that, let me know and we can try to figure out what’s going wrong.
